# Generated by Django 4.1.5 on 2023-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=500)),
                ('sm1', models.CharField(max_length=500)),
                ('sm2', models.CharField(max_length=500)),
                ('sm4', models.CharField(max_length=500)),
                ('sm3', models.CharField(max_length=500)),
            ],
        ),
    ]
