# Generated by Django 4.1.5 on 2023-03-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtests',
            name='testDescription',
            field=models.TextField(default=''),
        ),
    ]
