# Generated by Django 4.1.5 on 2023-04-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                default="/Images/placeholder.jpg", null=True, upload_to="Images/"
            ),
        ),
    ]
