# registation
POST http://127.0.0.1:8000/registration/
Content-Type: application/json

{
    "username": "sande",
    "email": "sandeshs@gmail.com",
    "password1": "shubhekshya",
    "password2": "shubhekshya"
}



### unsuccessul login request
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
    "username": "sandeshs@gmail.com",
    "email": "",
    "password": "shubhekshya1"
}


### successful login request
# @name login
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
    "username": "sandeshs@gmail.com",
    "email": "",
    "password": "shubhekshya"
}

### get userdetails
# @name userdetails
GET http://127.0.0.1:8000/accounts/user/
Content-Type: application/json

POST http://127.0.0.1:8000/core/a
Content-Type: application/json

{
    "username": "sandesh",
    "email": "sandeshshakya19@gmail.com",
    "password": "password"
}

### get preferredDoctor
# @name preferredDoctor
GET http://127.0.0.1:8000/doctor/doctorlist
Content-Type: application/json

### get appointmentlist
# @name appointmentlist
GET http://127.0.0.1:8000/appointments/appointmentlist
Content-Type: application/json

### post appointmentlist
# @name appointmentlist
POST http://127.0.0.1:8000/appointments/appointmentlist
Content-Type: application/json

    {
        "id": 2,
        "user_id": "2",
        "username": "ramua",
        "doctor_name": "shyamu",
        "doctor_id": 2,
        "appointment_date": "2023-02-19",
        "appointment_time": "12:15:00",
        "contact": 9812354671,
        "patient_name": "ramu",
        "age": 23,
        "gender": "Male",
        "user_patient_relation": "self"
    }