# registation
POST http://127.0.0.1:8000/registration/
Content-Type: application/json

{
    "username": "sande",
    "email": "sandeshs@gmail.com",
    "password1": "shubhekshya",
    "password2": "shubhekshya"
}



### unsuccessul login request
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
    "username": "sandeshs@gmail.com",
    "email": "",
    "password": "shubhekshya1"
}


### successful login request
# @name login
POST http://127.0.0.1:8000/accounts/login/
Content-Type: application/json

{
    "username": "sandeshs@gmail.com",
    "email": "",
    "password": "shubhekshya"
}

### get userdetails
# @name userdetails
GET http://127.0.0.1:8000/accounts/user/
Content-Type: application/json

POST http://127.0.0.1:8000/core/a
Content-Type: application/json

{
    "username": "sandesh",
    "email": "sandeshshakya19@gmail.com",
    "password": "password"
}

### get preferredDoctor
# @name preferredDoctor
GET http://127.0.0.1:8000/doctor/doctorlist
Content-Type: application/json

### get appointmentlist
# @name appointmentlist
GET http://127.0.0.1:8000/appointments/appointmentlist
Content-Type: application/json

### post appointmentlist
# @name appointmentlist
POST http://127.0.0.1:8000/appointments/appointmentlist
Content-Type: application/json

    {
        "userId": "2",
        "username": "ramua",
        "doctorName": "shyamu",
        "doctorId": 2,
        "appointmentDate": "2023-02-19 00:00:00.000",
        "appointmentTime": "12:15:00",
        "contact": 9812354671,
        "patientName": "ramu",
        "age": 23,
        "gender": "Male",
        "userPatientRelation": "self"
    }

   
### post labtestinglist
# @name labtestinglist
POST http://127.0.0.1:8000/labtestingappointments/labtestinglist
Content-Type: application/json

    {
        "id": 21,
        "userId": "20",
        "username": "shakya",
        "testList": [1],
        "collectionDate": "2023-02-28",
        "collectionTime": "16:07:00",
        "contact": 9812345678,
        "age": 23,
        "gender": "Male",
        "patientName": "dfs sdf",
        "userPatientRelation": "Self",
        "service": "On Site",
        "city": "No city.",
        "address": "No address.",
        "landmark": "No landmark."
    }