# Generated by Django 4.1.5 on 2023-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='labtestings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=60)),
                ('testList', models.TextField()),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('contact', models.IntegerField()),
                ('patientName', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('userPatientRelation', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=200)),
            ],
        ),
    ]
