# Generated by Django 4.1.5 on 2023-03-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_testing_appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestings',
            name='testList',
            field=models.TextField(default=''),
        ),
    ]
