# Generated by Django 4.1.5 on 2023-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availableFrom',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='availableTo',
            field=models.TimeField(blank=True, default='08:00:00', null=True),
        ),
    ]
