# Generated by Django 4.1.5 on 2023-02-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=60)),
                ('doctor_name', models.CharField(max_length=60)),
                ('doctor_id', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('contact', models.IntegerField()),
                ('patient_name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('user_patient_relation', models.CharField(max_length=20)),
            ],
        ),
    ]
