# Generated by Django 4.1.5 on 2023-03-07 11:48

from django.db import migrations, models
import report.file_type


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=300)),
                ('report', report.file_type.FileType(upload_to='uploads/')),
                ('remarks', models.CharField(max_length=600)),
            ],
        ),
    ]
